-- MySQL Script generated by MySQL Workbench
-- Mon Nov 26 10:38:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema IA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema IA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IA` DEFAULT CHARACTER SET utf8 ;
USE `IA` ;

-- -----------------------------------------------------
-- Table `IA`.`tipo_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IA`.`tipo_produto` (
  `idtipoProduto` INT NOT NULL,
  PRIMARY KEY (`idtipoProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IA`.`mesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IA`.`mesas` (
  `idMesas` INT NOT NULL,
  PRIMARY KEY (`idMesas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IA`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IA`.`clientes` (
  `idCliente` INT NOT NULL,
  `nome` INT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IA`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IA`.`pedidos` (
  `idPedidos` INT NOT NULL,
  `mesas_idMesas` INT NOT NULL,
  `clientes_idCliente` INT NOT NULL,
  PRIMARY KEY (`idPedidos`, `mesas_idMesas`, `clientes_idCliente`),
  INDEX `fk_pedidos_mesas1_idx` (`mesas_idMesas` ASC),
  INDEX `fk_pedidos_clientes1_idx` (`clientes_idCliente` ASC),
  CONSTRAINT `fk_pedidos_mesas1`
    FOREIGN KEY (`mesas_idMesas`)
    REFERENCES `IA`.`mesas` (`idMesas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_clientes1`
    FOREIGN KEY (`clientes_idCliente`)
    REFERENCES `IA`.`clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IA`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IA`.`produtos` (
  `idProduto` INT NOT NULL,
  `nome` VARCHAR(60) NULL,
  `preco` INT NULL,
  `tipo_produto_idtipoProduto` INT NOT NULL,
  `pedidos_idPedidos` INT NOT NULL,
  PRIMARY KEY (`idProduto`, `tipo_produto_idtipoProduto`, `pedidos_idPedidos`),
  INDEX `fk_produtos_tipo_produto_idx` (`tipo_produto_idtipoProduto` ASC),
  INDEX `fk_produtos_pedidos1_idx` (`pedidos_idPedidos` ASC),
  CONSTRAINT `fk_produtos_tipo_produto`
    FOREIGN KEY (`tipo_produto_idtipoProduto`)
    REFERENCES `IA`.`tipo_produto` (`idtipoProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_pedidos1`
    FOREIGN KEY (`pedidos_idPedidos`)
    REFERENCES `IA`.`pedidos` (`idPedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
