-- MySQL Script generated by MySQL Workbench
-- Thu Nov 22 13:01:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tea
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tea
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tea` DEFAULT CHARACTER SET utf8 ;
USE `tea` ;

-- -----------------------------------------------------
-- Table `tea`.`mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tea`.`mesa` (
  `mes_id` INT NOT NULL AUTO_INCREMENT,
  `mes_nome` VARCHAR(45) NOT NULL,
  `mes_liberada` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`mes_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tea`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tea`.`servicos` (
  `ser_id` INT NOT NULL AUTO_INCREMENT,
  `ser_nome` VARCHAR(45) NOT NULL,
  `ser_preco` FLOAT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`ser_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tea`.`tipo_itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tea`.`tipo_itens` (
  `tip_ite_id` INT NOT NULL AUTO_INCREMENT,
  `tip_ite_nome` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`tip_ite_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tea`.`itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tea`.`itens` (
  `ite_id` INT NOT NULL AUTO_INCREMENT,
  `ite_nome` VARCHAR(45) NOT NULL,
  `ite_preco` FLOAT NOT NULL,
  `tip_ite_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`ite_id`),
  INDEX `fk_itens_tipo_itens1_idx` (`tip_ite_id` ASC),
  CONSTRAINT `fk_itens_tipo_itens1`
    FOREIGN KEY (`tip_ite_id`)
    REFERENCES `tea`.`tipo_itens` (`tip_ite_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tea`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tea`.`tipo_usuario` (
  `tip_usu_id` INT NOT NULL AUTO_INCREMENT,
  `tip_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tip_usu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tea`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tea`.`usuarios` (
  `usu_id` INT NOT NULL AUTO_INCREMENT,
  `usu_nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `usuarioscol` VARCHAR(45) NOT NULL,
  `tip_usu_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`usu_id`),
  INDEX `fk_usuarios_tipo_usuario1_idx` (`tip_usu_id` ASC),
  CONSTRAINT `fk_usuarios_tipo_usuario1`
    FOREIGN KEY (`tip_usu_id`)
    REFERENCES `tea`.`tipo_usuario` (`tip_usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tea`.`atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tea`.`atendimento` (
  `ate_id` INT NOT NULL AUTO_INCREMENT,
  `mes_id` INT NOT NULL,
  `usu_id` INT NOT NULL,
  `fun_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`ate_id`),
  INDEX `fk_atendimento_mesa_idx` (`mes_id` ASC),
  INDEX `fk_atendimento_usuarios1_idx` (`usu_id` ASC),
  INDEX `fk_atendimento_usuarios2_idx` (`fun_id` ASC),
  CONSTRAINT `fk_atendimento_mesa`
    FOREIGN KEY (`mes_id`)
    REFERENCES `tea`.`mesa` (`mes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atendimento_usuarios1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `tea`.`usuarios` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atendimento_usuarios2`
    FOREIGN KEY (`fun_id`)
    REFERENCES `tea`.`usuarios` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tea`.`servicos_atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tea`.`servicos_atendimento` (
  `ser_ate_id` INT NOT NULL,
  `ate_id` INT NOT NULL,
  `ser_id` INT NOT NULL,
  `ser_preco` FLOAT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`ser_ate_id`),
  INDEX `fk_servicos_atendimento_atendimento1_idx` (`ate_id` ASC),
  INDEX `fk_servicos_atendimento_servicos1_idx` (`ser_id` ASC),
  CONSTRAINT `fk_servicos_atendimento_atendimento1`
    FOREIGN KEY (`ate_id`)
    REFERENCES `tea`.`atendimento` (`ate_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicos_atendimento_servicos1`
    FOREIGN KEY (`ser_id`)
    REFERENCES `tea`.`servicos` (`ser_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tea`.`itens_atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tea`.`itens_atendimento` (
  `ite_ate_id` INT NOT NULL AUTO_INCREMENT,
  `ate_id` INT NOT NULL,
  `ite_preco` FLOAT NOT NULL,
  `ite_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`ite_ate_id`),
  INDEX `fk_itens_atendimento_atendimento1_idx` (`ate_id` ASC),
  INDEX `fk_itens_atendimento_itens1_idx` (`ite_id` ASC),
  CONSTRAINT `fk_itens_atendimento_atendimento1`
    FOREIGN KEY (`ate_id`)
    REFERENCES `tea`.`atendimento` (`ate_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_atendimento_itens1`
    FOREIGN KEY (`ite_id`)
    REFERENCES `tea`.`itens` (`ite_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

RENAME TABLE mesa TO mesas;

ALTER TABLE `usuarios`  DROP `usuarioscol`;

rename table tipo_usuario to tipo_usuarios;

insert into tipo_usuarios (tip_nome) values ('Administrador');

insert into tipo_usuarios (tip_nome) values ('Funcionário');

insert into tipo_usuarios (tip_nome) values ('Cliente');

RENAME table itens_atendimento to itens_atendimentos;

ALTER TABLE `servicos` CHANGE `ser_preco` `ser_preco` VARCHAR(6) NOT NULL;

ALTER TABLE `atendimento` CHANGE `fun_id` `fun_id` INT(11) NULL;

ALTER TABLE `servicos_atendimento` CHANGE `ser_ate_id` `ser_ate_id` INT(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `servicos_atendimento` CHANGE `ser_preco` `ser_preco` VARCHAR(6) NOT NULL;

ALTER TABLE `itens_atendimentos` CHANGE `ite_preco` `ite_preco` VARCHAR(6) NOT NULL;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
